name: 04-using-actions
on: push
jobs:
    build:
        runs-on: Ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app # anothing way of including directory for jobs
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Printing folder 
              run:  ls  
            - name: setup Node-app
              uses: actions/checkout@v3
              with:
                 node-version: '20.x'
            - name: Install dependencies
              run:  npm ci
            - name: Run Unit Test
              run: npm run test
              

        #0 checkout the code from repo
        #1. install deps for react-app
        #2. run atomated test case
