name: 04-using-actions
on: workflow_dispatch
jobs:
    build:
        runs-on: Ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Printing folder 
              run:  ls     
        #0 checkout the code from repo
        #1. install deps for react-app
        #2. run atomated test case
