name: 04-using-actions
on: workflow_dispatch
jobs:
    build:
        runs-on: Ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Printing folder 
              run:  ls  
            - name: setup Node-app
              uses: actions/checkout@v3
            - name: Install dependencies
              run:  npm ci
              working-directory: 04-using-actions/react-app
            - name: Run Unit Test
              run: npm run test
              working-directory: 04-using-actions/react-app

        #0 checkout the code from repo
        #1. install deps for react-app
        #2. run atomated test case
