name: 07.1-resuable-workflow
on:
   workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/07-reusable-workflows.yaml
        with:
            taget-directory: dummy-dir
    print-outputs:
        runs-on: Ubuntu-latest
        needs: deploy
        steps:
            - name: Print outputs
              run: |
                echo" Build-status: ${{ needs.deploy.outputs.build-status }}
                echo" URL: ${{ needs.deploy.outputs.url }}

